export { default as Art } from './Art'
export { default as FluidBg } from './FluidBg'
export { default as Head } from './Head'
export { default as Header } from './Header'
export { default as Music } from './Music'
